### ISSUE TITLE
Setting raw string value 

### ISSUE THREAD

**Issue by neeilya** [PeakTai/vue-html5-editor#10]
Hello.
Can I somehow assign raw string to content or any other corresponding attribute?
`<vue-html5-editor :content="This is content" ..></vue-html5-editor>`
or 
`<vue-html5-editor :value="This is content" ..></vue-html5-editor>`

The reason I have to do this is that I cannot bind javascript variable to :content attribute since I manipulate it in laravel blade template file.

**Comment by PeakTai** [comment]
It has been supported by V0.5.0
