### ISSUE TITLE
Two way bindings

### ISSUE THREAD

**Issue by Wifsimster** [PeakTai/vue-html5-editor#11]
First, thanks for this awesome and fonctional plugin !

Second, i think it would be nice to add in the documentation the **two way bindings**.
I spend time searching for a solution, almost remove your plugin :/

`:content.sync="content"`

**Comment by PeakTai** [comment]
Two way bindings is optional.
What is the vue version you are using?

**Comment by Wifsimster** [comment]
I'm using the latest 1.0.28.

And by the way, since last Vue version `v-if` can't be with a `v-for` directive in same time ;)
