### ISSUE TITLE
Do not use built-in or reserved HTML elements as component id

### ISSUE THREAD

**Issue by zgabievi** [PeakTai/vue-html5-editor#13]
- [Vue warn]: Do not use built-in or reserved HTML elements as component id: text 
- [Vue warn]: Do not use built-in or reserved HTML elements as component id: font 
- [Vue warn]: Do not use built-in or reserved HTML elements as component id: link 
- [Vue warn]: Do not use built-in or reserved HTML elements as component id: image

**Comment by PeakTai** [comment]
Thank you for your feedback!
I have fixed it in v0.5.1.
