### ISSUE TITLE
Add class manipulation in prop

### ISSUE THREAD

**Issue by Wifsimster** [PeakTai/vue-html5-editor#18]
It will be good to be able to manipulate some style properties through :props.

Actually, i would like to change the current **z-index** value of `.vue-html-5-editor` and `.tools`.

**Comment by PeakTai** [comment]
Vue support it native.
```html
<!--custom-class will add to component root element-->
<editor class="custom-class"></editor>
```

**Comment by Wifsimster** [comment]
Yes but you can't manipulate inner class of the component from the parent. Props helps with that.
