### ISSUE TITLE
two way bings in vue2.0

### ISSUE THREAD

**Issue by haixu777** [PeakTai/vue-html5-editor#27]
when i try to assign some text in content, the console said that 

```
" Error in callback for watcher "content": "
```

i try use "content.sync" before, but it dosen't work in Vue2.0

Is there any way to solve it?

**Comment by stexine** [comment]
same problem here

**Comment by PeakTai** [comment]
Please use version 1.0.0 !

Two way binding already had removed by vue2.0 .You can sync content through  the change event on editor component,now.

**Comment by JustinWang24** [comment]
I'm using 1.0.0, but still got this problem. Could you please provide a sample code? Thanks.

**Comment by PeakTai** [comment]
See the examples. https://github.com/PeakTai/vue-html5-editor/tree/master/example
