### ISSUE TITLE
使用该组件无法获得数据是什么情况？

### ISSUE THREAD

**Issue by fengcms** [PeakTai/vue-html5-editor#29]
mian.js
```js
import VueHtml5Editor from 'vue-html5-editor'
Vue.use(VueHtml5Editor)
```
引用
```html
<vue-html5-editor :content="dat.content" :height="300"></vue-html5-editor>
```
编辑器展示出来了。但是往里面填写内容后，获取不到数据，已有的数据也无法绑定到编辑器里面。

**Comment by PeakTai** [comment]
新版本的同步需要通过change事件，可以看下这个demo:

https://github.com/PeakTai/vue-html5-editor/blob/master/example/basic.html

**Comment by fengcms** [comment]
好的，非常感谢，建议修改下首页的说明文档

**Comment by fengcms** [comment]
抑郁，现在能够提交内容，加上了change事件，但是从接口获取的数据无法在编辑器展示，是什么情况？ @PeakTai

**Comment by PeakTai** [comment]
@fengcms 给点演示代码，我看下。

**Comment by PeakTai** [comment]
#30 你的问题可能和这个一样，我已经推送了新版本到npm，更新下再试试。

**Comment by fengcms** [comment]
@PeakTai 嗯，升级到最新版之后，问题解决了。谢谢你开发了这个编辑器，集成其他编辑器太困难了。。。
