### ISSUE TITLE
支持自动增高

### ISSUE THREAD

**Issue by PeakTai** [PeakTai/vue-html5-editor#3]
组件增加属性`auto-height`来控制，默认为`true`

**Comment by hefengxian** [comment]
用Vue试用了这么多组件，唯一这个是无痛解决了问题的；非常轻量级，纯Vue编写的。非常感谢作者，但是为什么这么好的组件才几颗星呢？我提几个建议：
 
1. 组件增加可以拖动大小功能
2. 实现更多其他编辑器的小功能（字数统计等）
3. 将组件国际化（文档等使用英文编写，npm上的文档也是）
4. 去Vue的论坛/作者/awesome vue这些地方推一下这个组件，让大家知道这个组件，提高下知名度

**Comment by PeakTai** [comment]
@hefengxian 感谢支持，这些功能都会考虑的。

编辑器起初是为了团队开发的，追求速度，很多东西没有考虑。
目前公司团队正在使用，会继续维护更新。
