### ISSUE TITLE
content更新后，Error in callback for watcher "content"

### ISSUE THREAD

**Issue by liCat** [PeakTai/vue-html5-editor#30]
你在watch里把$refs.content写成$res.content了，能及时更正吗？

**Comment by haixu777** [comment]
@liCat 
thank u soooooooooo much!!!!
u save my day!

**Comment by PeakTai** [comment]
好的，我看下，马上更新下

**Comment by PeakTai** [comment]
已经推送1.0.1版本到npm了，可以更新下。
