### ISSUE TITLE
上传图片成功，但没法在富文本框显示图片

### ISSUE THREAD

**Issue by hin-longkid** [PeakTai/vue-html5-editor#32]
图片上传成功，但报错，信息如下：
[Vue warn]: Property or method "progressComputable" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <DashboardImage>)

options配置如下：
uploadHandler: function (responseText) {
  // default accept json data like  {ok:false,msg:'unexpected'} or {ok:true,data:'image url'}
  var json = JSON.parse(responseText)
  if (!json.result) {
    alert(json)
  } else {
    return 'http://domain/file/' + json.result.fileid
  }
}

**Comment by PeakTai** [comment]
使用的是什么版本？

**Comment by PeakTai** [comment]
感谢反馈，问题已经修复，请更新到1.0.2版本.
