### ISSUE TITLE
fragment instance issue

### ISSUE THREAD

**Issue by woshihaoren** [PeakTai/vue-html5-editor#4]
@PeakTai 
Use vue init   initialization project
```vue init webpack test```
replace default's App component
```
<template>
  <div id="app">
  <editor :content="content" :height="500"></editor>
  <div style="margin-top:40px">
    <div> The HTML contents are as follows:</div>
    <hr>
    <div >{{{content}}}</div>
  </div>
  </div>
</template>

<script>
import Hello from './components/Hello'
import editor from 'vue-html5-editor'

export default {
  components: {
    Hello,
    editor
  }
}
</script>
```
### console
vue.common.js?1090:1019[Vue warn]: Attributes "content", ":height" are ignored on component <editor> because the component is a fragment instance: http://vuejs.org/guide/components.html#Fragment-Instance

**Comment by PeakTai** [comment]
Editor can't use directly as a local child component.

It must install global via `Vue.use()`,reference to the examples.

**Comment by woshihaoren** [comment]
Yeah,  you are right
