### ISSUE TITLE
插件图标渲染不出来，放开标题显示，点击标题报死循环

### ISSUE THREAD

**Issue by hejielhwx** [PeakTai/vue-html5-editor#45]
You may have an infinite update loop in a component render function

![image](https://cloud.githubusercontent.com/assets/13311941/24347293/655b0282-130a-11e7-890b-854a5e155633.png)

**Comment by klexxp** [comment]
Same problem here. I don't even get that error message. The component just hangs until the page brakes.

**Comment by cdmin207078** [comment]
+1

**Comment by AbandonedDrama** [comment]
+1

**Comment by PeakTai** [comment]
这个问题之前解决过,请问用的什么版本?

**Comment by PeakTai** [comment]
这个问题和 #49 一样

**Comment by PeakTai** [comment]
问题已解决,请从npm升级编辑器到到1.0.3版本
