### ISSUE TITLE
点击模块图标，页面假死

### ISSUE THREAD

**Issue by kshan** [PeakTai/vue-html5-editor#49]
系统：macOS Sierra 10.12.4

浏览器：Safari 10.1、Chrome 56.0.2924.87

下载回来的 Demo 没有问题，也不知道跟项目代码有什么冲突，页面假死，无法 debug.

**Comment by AbandonedDrama** [comment]
+1

**Comment by williamjava** [comment]
+1

**Comment by doudoubi** [comment]
+1

**Comment by PeakTai** [comment]
vue和编辑器版本是多少?

**Comment by AbandonedDrama** [comment]
"vue-html5-editor": "^1.0.2"
"vue": "^2.1.0"

**Comment by PeakTai** [comment]
我已经找到原因了,https://github.com/vuejs/vue/issues/5191  , vue2.2.5之后,对组件声明的属性重新赋值也会触发updated,编辑器在updated里对属性进行了赋值导致无限循环.
