### ISSUE TITLE
[建议]全部删除文字后data为空而不是br标签

### ISSUE THREAD

**Issue by yangyichen** [PeakTai/vue-html5-editor#52]
而且有时候可以全部删除变成一个空的string，有时候缺删不掉。
例如：插入分割线后删除，可以全部删除，如果加粗或者倾斜文字后全部删除会变成<br>标签

**Comment by yangyichen** [comment]
刚刚查询了一下是contenteditable这个属性的问题，那么是否考虑用input代替呢？

**Comment by PeakTai** [comment]
用input肯定做不了富文本编辑.

这个特性是浏览器来决定的, 一般没什么影响.

如果想做这样的处理,可以在前端或后端做下过滤.对整个编辑的html内容取纯文本,如果是空串,将html改为空串.

**Comment by yangyichen** [comment]
嗯，我用了正则匹配了一下，可以达到我的目的了。
感谢。
