### ISSUE TITLE
[bug]自定义模块排序问题

### ISSUE THREAD

**Issue by yangyichen** [PeakTai/vue-html5-editor#56]
自定义了一个modules，我想把这个modules放在中间部分，但是实际上却是在最后的

```
visibleModules: [
        "text",
        "color",
        "cust-font",
        "align",
        "hr",
        "full-screen",
    ],
```
实际上：
![image](https://cloud.githubusercontent.com/assets/8776272/25161330/e68d174c-24ed-11e7-9ac8-c5daa3252bb4.png)
最后一个是我自己定义的cust-font模块，期望的是在排在第三位

**Comment by PeakTai** [comment]
感谢反馈,我刚测了下,确实有问题.

**Comment by PeakTai** [comment]
这个问题已经解决,请更新到1.1.1版本.

**Comment by yangyichen** [comment]
@PeakTai 非常感谢 😃
