### ISSUE TITLE
感谢分享这么好的插件，请问怎么增加标题编辑功能，尝试了一下没有成功

### ISSUE THREAD

**Issue by scoolor** [PeakTai/vue-html5-editor#6]
标题编辑功能还是用的比较多，想增加该功能，尝试没有成功，麻烦指点一下，或者官方支持自然最好了

**Comment by PeakTai** [comment]
感谢支持！我打算下个版本支持设置字体大小和对齐方式。

程序结构我还在优化，目前扩展只能改源码。

可以尝试改buttons.js并添加对应的dashboard组件。

**Comment by scoolor** [comment]
@PeakTai ok，我研究一下，谢谢

**Comment by PeakTai** [comment]
版本0.4.0已经实现这些功能
