### ISSUE TITLE
怎么在已经加载完组件后再修改上传图片的url

### ISSUE THREAD

**Issue by DuckDeck** [PeakTai/vue-html5-editor#71]
如题，当引入该组件时，可以从options设定上传图片的url， 但是只能设定一次，如果后面要修应该怎么写设置？

**Comment by PeakTai** [comment]
暂时不支持这么做，你可以通过动态组件来实现，在需要改变的时候，重新初始化一个子组件实例。

```html
<div v-if='editor' :is='editor'></div>
```

```js
export default{
    data: {editor:null}
    methods:{
        changeEditor(){
            this.editor = new VueHtml5Editor(options)
        }
    }
}
```

**Comment by DuckDeck** [comment]
那如果这样的话，怎么把data里面的editor放到html标签里面呢

**Comment by DuckDeck** [comment]
知道你的方法了，但是还是不行啊，上面的的的按钮全部点不了了。不知道为什么会这样。
我后现用另一个思路解决了，就是拦截全局ajax请求并更改url，就可以了

**Comment by DuckDeck** [comment]
我这个项目每次上传图片的url都不一样，所以这个功能后面更新还是可以加上去的
